name: Send Jagran News

on:
  schedule:
    - cron: "*/5 * * * *"   # हर 5 मिनट पर चलेगा
  workflow_dispatch:         # Manual run का option भी होगा

jobs:
  run-news-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: python main.py
        
